all: build view

build:
	/usr/bin/pdflatex Introduction_to_Hadoop
	/usr/bin/pdflatex Introduction_to_Hadoop
	/usr/bin/pdflatex Introduction_to_Hadoop
	/usr/bin/pdflatex Introduction_to_Hadoop

view:
	acroread Introduction_to_Hadoop.pdf

clean:
	rm -f *.toc *.snm  *.out *.nav *.log *.aux *.vrb *~

